version: "3.6"
services:
  nginx:
    image: engelsystem-nginx
    build:
      context: ..
      dockerfile: contrib/nginx/Dockerfile
    restart: always
    ports:
      - 5000:80
    volumes:
      - static:/var/www/
    networks:
      - internal
    depends_on:
      - engelsystem
  engelsystem:
    image: engelsystem
    build:
      context: ..
      dockerfile: contrib/Dockerfile
    restart: always
    ports:
       - 9100:9000
    environment:
      MYSQL_HOST: database
      MYSQL_USER: engelsystem
      MYSQL_PASSWORD: engelsystem
      MYSQL_DATABASE: engelsystem
      NO_REPLY_MAIL: helfer@wuerzburg18.de
      SMTPHOST: smtp
    volumes:
      - static:/var/www/
    networks:
      - internal
      - database
      - mail
    depends_on:
      - database
  database:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_DATABASE: engelsystem
      MYSQL_USER: engelsystem
      MYSQL_PASSWORD: engelsystem
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    volumes:
      - db:/var/lib/mysql
    networks:
      - database
  smtp:
    image: mail_relay
    restart: always
    networks:
      - mail
volumes:
  db:
  static:

networks:
  internal:
  database:
  mail:
